"""Adding tables

Revision ID: 3de764add30f
Revises: 
Create Date: 2020-06-06 14:09:38.500328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de764add30f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('username', sa.String(
                        length=50), nullable=False),
                    sa.Column('password', sa.String(
                        length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('decks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=30), nullable=False),
                    sa.Column('description', sa.String(
                        length=300), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('cards',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('deck_id', sa.Integer(), nullable=False),
                    sa.Column('question', sa.String(
                        length=200), nullable=False),
                    sa.Column('answer', sa.String(length=200), nullable=False),
                    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('favorite',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('deck_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('completed',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('card_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed')
    op.drop_table('favorite')
    op.drop_table('cards')
    op.drop_table('decks')
    op.drop_table('users')
    # ### end Alembic commands ###
